# Generated by Django 5.2.17 on 2026-08-10 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', 'session_id', 'created_at'], name='chat_user_session_created_idx'),
        ),
    ]
