# Generated by Django 5.2.17 on 2026-08-25 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_chatmessage_chat_user_session_created_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NaviMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('clave', models.CharField(max_length=80, verbose_name='Clave')),
                ('valor', models.CharField(max_length=200, verbose_name='Valor')),
                ('fuente', models.CharField(choices=[('auto', 'Aprendido automáticamente'), ('usuario', 'Guardado por el usuario')], default='auto', max_length=8, verbose_name='Fuente')),
                ('usos', models.PositiveIntegerField(default=1, verbose_name='Usos')),
                ('ultimo_uso', models.DateTimeField(auto_now=True, verbose_name='Último uso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Memoria del asistente',
                'verbose_name_plural': 'Memorias del asistente',
                'ordering': ['-usos', '-ultimo_uso'],
                'indexes': [models.Index(fields=['user', 'usos'], name='memi_user_usos_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'clave'), name='navimemory_user_clave_uniq')],
            },
        ),
    ]
