# Generated by Django 5.2.17 on 2026-10-08 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_end_gte_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cuota periódica referencial (opcional).', max_digits=20, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(choices=[('USD', '$ — Dólar estadounidense'), ('VES', 'Bs — Bolívar (VES)'), ('EUR', '€ — Euro')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gt', 0), _connector='OR'), name='subscription_amount_gt_0', violation_error_message='El monto debe ser mayor a cero o estar vacío.'),
        ),
    ]
