# Generated by Django 5.2.17 on 2026-08-04 19:29

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('icon', models.CharField(blank=True, default='tag', max_length=40, verbose_name='Icono')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='egreso', max_length=10, verbose_name='Tipo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Por defecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['tipo', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Nota')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('tipo', models.CharField(choices=[('cobro', 'Cobro (ingreso)'), ('pago', 'Pago (egreso)')], max_length=10, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12, verbose_name='Estado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('USD', '$ — Dólar estadounidense'), ('VES', 'Bs — Bolívar (VES)'), ('EUR', '€ — Euro')], max_length=3, verbose_name='Moneda')),
                ('monto_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto en USD')),
                ('tasa_usd', models.DecimalField(decimal_places=4, default=1, max_digits=20, verbose_name='Tasa usada')),
                ('fuente_tasa', models.CharField(choices=[('oficial', 'Tasa oficial (BCV) vía DolarApi'), ('usd', 'Operación en USD (tasa 1)'), ('manual', 'Tasa manual'), ('fallback', 'Tasa de emergencia (sin API)')], default='fallback', max_length=10, verbose_name='Fuente de tasa')),
                ('concepto', models.CharField(blank=True, max_length=160, verbose_name='Concepto')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vence el')),
                ('fecha_pagado', models.DateTimeField(blank=True, null=True, verbose_name='Pagado el')),
                ('remind_me', models.BooleanField(default=True, help_text='Sobrescribe la regla global de recordatorios si está desactivado.', verbose_name='Recordar')),
                ('nota', models.TextField(blank=True, verbose_name='Nota')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.category', verbose_name='Categoría')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.contact', verbose_name='Contacto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallets.wallet', verbose_name='Billetera')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'tipo'), name='uniq_category_per_user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'estado'], name='transaction_user_id_20e1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'fecha_vencimiento'], name='transaction_user_id_d629b8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'fecha'], name='transaction_user_id_4c96bf_idx'),
        ),
    ]
