# Generated by Django 5.2.17 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reminder_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Anticipación del recordatorio; si queda vacío se usa la regla global del usuario (ADR-09).",
                null=True,
                verbose_name="Avisar N días antes",
            ),
        ),
    ]
