# Generated by Django 5.2.17 on 2026-08-07 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_reminder_days'),
        ('wallets', '0003_wallet_tipo_ahorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dest_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='wallets.wallet', verbose_name='Billetera destino'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='moneda_destino',
            field=models.CharField(blank=True, choices=[('USD', '$ — Dólar estadounidense'), ('VES', 'Bs — Bolívar (VES)'), ('EUR', '€ — Euro')], max_length=3, verbose_name='Moneda destino'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='monto_destino',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto en destino'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tasa_fuente',
            field=models.CharField(choices=[('oficial', 'Tasa oficial (BCV)'), ('manual', 'Tasa personalizada')], default='manual', max_length=10, verbose_name='Fuente de la tasa'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tasa_uso',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=20, verbose_name='Tasa usada en el traspaso'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tipo',
            field=models.CharField(choices=[('cobro', 'Cobro (ingreso)'), ('pago', 'Pago (egreso)'), ('transferencia', 'Transferencia entre cuentas')], max_length=13, verbose_name='Tipo'),
        ),
    ]
