# Generated by Django 5.2.17 on 2026-08-10 00:47

from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Q


def clear_invalid_vencimiento(apps, schema_editor):
    """Limpieza de datos dev (A10): antes de la constraint
    ``fecha_vencimiento >= fecha`` se anulan los vencimientos inválidos
    (vencimiento anterior a la fecha de la operación). En agosto-2026 había
    una sola fila en dev ("Cine", cancelada); la API ya rechaza este caso al
    crear/editar. En bases de prueba no hay datos, es un no-op.
    """
    Transaction = apps.get_model("transactions", "Transaction")
    Transaction.objects.filter(
        Q(fecha_vencimiento__isnull=False) & Q(fecha_vencimiento__lt=F("fecha"))
    ).update(fecha_vencimiento=None)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transfer_fields'),
        ('wallets', '0005_balanceauditlog_alter_wallet_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_manager_name': 'objects', 'ordering': ['-fecha'], 'verbose_name': 'Operación', 'verbose_name_plural': 'Operaciones'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete (C4): la operación se oculta de la API pero conserva su historial.', verbose_name='Borrada'),
        ),
        migrations.RunPython(
            clear_invalid_vencimiento,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'estado', '-fecha_pagado'], name='transaction_user_id_99a66d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'tipo', 'fecha'], name='transaction_user_id_7d56ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='transaction_monto_gt_0', violation_error_message='El monto debe ser mayor a cero.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('tasa_usd__gt', 0)), name='transaction_tasa_usd_gt_0', violation_error_message='La tasa usada debe ser mayor a cero.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['pendiente', 'pagado', 'cancelado'])), name='transaction_estado_valid', violation_error_message='Estado de operación inválido.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['cobro', 'pago', 'transferencia'])), name='transaction_tipo_valid', violation_error_message='Tipo de operación inválido.'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vencimiento__isnull', True), ('fecha_vencimiento__gte', models.F('fecha')), _connector='OR'), name='transaction_vencimiento_gte_fecha', violation_error_message='El vencimiento no puede ser anterior a la fecha.'),
        ),
    ]
