# Generated by Django 5.2.17 on 2026-10-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transfer_integrity_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('crm_invoice', 'CRM: factura'), ('crm_order', 'CRM: pedido'), ('assistant', 'Asistente Navi'), ('subscription', 'Mensualidad'), ('checklist', 'Lista de compras'), ('transfer', 'Transferencia')], default='manual', help_text='Flujo que generó la operación (manual, CRM, asistente, etc.).', max_length=12, verbose_name='Origen'),
        ),
    ]
