# Generated by Django 5.2.17 on 2026-08-04 19:29

import apps.accounts.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Identificador único; se normaliza a minúsculas.', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('base_currency', models.CharField(choices=[('USD', '$ — Dólar estadounidense'), ('VES', 'Bs — Bolívar (VES)'), ('EUR', '€ — Euro')], default='USD', help_text='Moneda con la que el usuario quiere ver sus finanzas (ADR-10).', max_length=3, verbose_name='Moneda base')),
                ('language', models.CharField(choices=[('es', 'Español')], default='es', max_length=10, verbose_name='Idioma')),
                ('timezone_name', models.CharField(default='America/Caracas', help_text='Ej. America/Caracas (UTC-4) para Venezuela.', max_length=64, verbose_name='Zona horaria')),
                ('reminder_days', models.PositiveSmallIntegerField(default=3, help_text='Regla global: avisar pagos que vencen en N días (ADR-09).', verbose_name='Días de recordatorio')),
                ('is_active', models.BooleanField(default=False, help_text='Se activa tras verificar el email.', verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrado el')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('used', models.BooleanField(default=False, verbose_name='Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Verificación de email',
                'verbose_name_plural': 'Verificaciones de email',
            },
        ),
    ]
