# Generated by Django 5.2.17 on 2026-08-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('terms', 'Términos y Condiciones'), ('privacy', 'Política de Privacidad')], max_length=20, verbose_name='Tipo de documento')),
                ('version', models.CharField(help_text='Ej. v1-2026-08', max_length=30, verbose_name='Versión')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido (Markdown)')),
                ('is_active', models.BooleanField(default=False, help_text='Solo una versión por tipo puede estar activa a la vez.', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('effective_at', models.DateTimeField(blank=True, help_text='Fecha desde la que aplica esta versión. Si no se indica, se usa created_at.', null=True, verbose_name='Vigente desde')),
            ],
            options={
                'verbose_name': 'Documento legal',
                'verbose_name_plural': 'Documentos legales',
                'ordering': ['doc_type', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('doc_type',), name='unique_active_legal_doc_per_type')],
            },
        ),
    ]
