# Generated by McAfee-style data seed: canonical legal documents.
# ---------------------------------------------------------------------------
# Siembra/sobrescribe la versión activa de los documentos legales (Términos y
# Privacidad) usados tanto por el modal de registro como por el de perfil.
#
# El contenido canónico vive aquí (y en apps/web/src/features/legal en su
# respaldo estático) de forma reproducible en cualquier entorno. La operación
# es idempotente: actualiza la fila activa de cada tipo o la crea si no existe.
# ---------------------------------------------------------------------------

from datetime import datetime, timezone

import django.utils.timezone as dj_timezone
from django.db import migrations

TERMS_CONTENT = """# Términos y Condiciones de Uso

**Versión:** v1-2026-08
**Vigente desde:** 10 de agosto de 2026

## 1. Aceptación de los Términos

Al crear una cuenta en NaviCash, aceptas estos Términos y Condiciones y nuestra Política de Privacidad. Si no estás de acuerdo, no uses el servicio.

## 2. Descripción del Servicio

NaviCash es una aplicación de gestión de finanzas personales que permite:
- Registrar ingresos, gastos y transferencias entre tus cuentas
- Gestionar metas de ahorro y suscripciones recurrentes
- Recibir recordatorios de vencimientos
- Consultar saldos y reportes
- Interactuar con Navi, un asistente conversacional (IA) para registrar operaciones por voz o texto

**NaviCash NO es un banco, entidad financiera, ni asesor de inversiones.**

No custodia fondos, no realiza movimientos de dinero real y no ofrece asesoría financiera, legal ni tributaria.

## 3. Cuenta de Usuario

- Debes ser mayor de 18 años (o la mayoría de edad en tu jurisdicción)
- Eres responsable de mantener confidenciales tu email y contraseña
- Debes notificarnos inmediatamente cualquier uso no autorizado de tu cuenta
- Nos reservamos el derecho de suspender o eliminar cuentas que incumplan estos Términos

## 4. Uso Permitido y Prohibido

**Permitido:** uso personal, legal y legítimo para organizar tus finanzas.

**Prohibido:**

- Uso para actividades fraudulentas, lavado de dinero o ilegales
- Ingeniería inversa, scraping o acceso no autorizado a la API
- Compartir credenciales o permitir acceso a terceros
- Interferir con la seguridad o estabilidad del servicio

## 5. Datos y Privacidad

El tratamiento de tus datos se rige por nuestra Política de Privacidad. En resumen:
- Tus datos financieros son tuyos y no los vendemos
- Solo accedemos a ellos para prestarte el servicio
- Puedes solicitar la eliminación de tu cuenta y datos en cualquier momento

## 6. Asistente Navi (IA)

Navi es un asistente basado en modelos de lenguaje (LLM) con fallback determinista.
- Puede cometer errores: verifica siempre la información importante
- No es asesor financiero: sus respuestas son orientativas
- Las operaciones que sugiere requieren tu confirmación explícita
- NaviCash no se responsabiliza por decisiones tomadas basadas en sus respuestas

## 7. Tasas de Cambio

Las tasas BCV (Banco Central de Venezuela) se obtienen de fuentes públicas y se cachean.
- Son referenciales y pueden diferir del mercado real
- NaviCash no garantiza su exactitud ni disponibilidad continua

## 8. Disponibilidad y Cambios

- El servicio se ofrece tal cual, sin garantía de disponibilidad ininterrumpida
- Podemos introducir mejoras, cambios o suspender el servicio con aviso razonable
- Los cambios relevantes a estos Términos se notificarán por email

## 9. Limitación de Responsabilidad

En la máxima medida permitida por la ley:
- NaviCash no responde por errores de cálculo, decisiones financieras basadas en la app, ni daños indirectos
- La responsabilidad total se limita al monto pagado por el usuario (si aplica) en los últimos 12 meses

## 10. Ley Aplicable y Jurisdicción

Estos Términos se rigen por las leyes de la República Bolivariana de Venezuela. Cualquier disputa se resolverá en los tribunales competentes de Caracas.

## 11. Contacto

Para dudas sobre estos Términos o el tratamiento de tus datos: **soporte@navicash.app**"""

PRIVACY_CONTENT = """# Política de Privacidad

**Versión:** v1-2026-08
**Vigente desde:** 10 de agosto de 2026

## 1. Responsable del Tratamiento

**NaviCash** (en adelante, «nosotros», «nuestro», «la App») es el responsable del tratamiento de tus datos personales. Contacto: **soporte@navicash.app**

## 2. Qué Datos Recopilamos

### Datos que nos proporcionas

- **Cuenta**: email, nombre, apellido, teléfono (opcional), contraseña (hash)
- **Perfil**: moneda base, zona horaria, idioma, preferencias de recordatorios
- **Financieros**: transacciones (monto, moneda, categoría, concepto, fecha), cuentas/billeteras, metas de ahorro, suscripciones, contactos
- **Interacciones con Navi**: mensajes de chat/voz para registrar operaciones

### Datos que generamos automáticamente

- Tokens de verificación, recuperación de contraseña, sesiones (JWT)
- Logs de acceso, auditoría de saldos, preferencias de notificaciones

## 3. Finalidad y Base Legal

| Finalidad | Base Legal (GDPR/LOPD) |
| --- | --- |
| Crear y gestionar tu cuenta | Ejecución de contrato (Art. 6.1.b) |
| Enviar verificación y recuperación de contraseña | Interés legítimo / Consentimiento |
| Procesar transacciones y generar reportes | Ejecución de contrato |
| Enviar recordatorios y notificaciones | Interés legítimo / Consentimiento |
| Mejorar el servicio (analytics anónimos) | Interés legítimo |
| Cumplir obligaciones legales | Obligación legal |

## 4. Compartición de Datos

**No vendemos tus datos.** Solo compartimos con:
- Proveedores de infraestructura (hosting, email, BD) bajo contrato de encargo de tratamiento
- Autoridades competentes si nos lo exige la ley
- Servicios de IA (LLM) para Navi: **solo el mensaje actual y contexto mínimo**, sin identificar al usuario

## 5. Transferencias Internacionales

Nuestros servidores pueden estar en EE. UU. / UE. Si hay transferencia, usamos cláusulas contractuales tipo (SCC) u otras garantías adecuadas.

## 6. Tus Derechos

Puedes ejercer en cualquier momento (escribe a soporte@navicash.app):
- **Acceso**: saber qué datos tenemos
- **Rectificación**: corregir datos inexactos
- **Supresión**: eliminar tu cuenta y datos (salvo obligación legal de conservación)
- **Limitación**: restringir el tratamiento
- **Portabilidad**: recibir tus datos en formato estructurado
- **Oposición**: oponerte al tratamiento por interés legítimo
- **No decisiones automatizadas**: no tomamos decisiones que te afecten significativamente solo por algoritmos

## 7. Conservación

- Datos de cuenta: mientras la cuenta esté activa + 3 años tras eliminación
- Transacciones: 10 años (obligación contable/fiscal)
- Logs de acceso: 1 año
- Tokens de sesión: 30 días (refresh) / 15 min (access)

## 8. Seguridad

- Contraseñas: hash Argon2 (nunca en claro)
- Comunicaciones: HTTPS/TLS 1.3
- JWT: access 15 min + refresh 30 días en cookie httpOnly + rotación + blacklist
- CAPTCHA (Turnstile) en registro/login
- Rate limiting por usuario/IP

## 9. Menores de Edad

La App no está dirigida a menores de 18 años. No recopilamos datos de menores conscientemente.

## 10. Cambios en esta Política

Notificaremos cambios relevantes por email y en la App. La versión actualizada quedará publicada aquí.

## 11. Contacto

Delegado de Protección de Datos: **soporte@navicash.app**"""


def upsert_documents(apps, schema_editor):
    LegalDocument = apps.get_model("accounts", "LegalDocument")
    effective_at = dj_timezone.make_aware(datetime(2026, 8, 10), timezone.utc)

    documents = [
        {
            "doc_type": "terms",
            "version": "v1-2026-08",
            "title": "Términos y Condiciones de Uso",
        },
        {
            "doc_type": "privacy",
            "version": "v1-2026-08",
            "title": "Política de Privacidad",
        },
    ]
    contents = {
        "terms": TERMS_CONTENT,
        "privacy": PRIVACY_CONTENT,
    }

    for spec in documents:
        doc_type = spec["doc_type"]
        doc = (
            LegalDocument.objects.filter(doc_type=doc_type, is_active=True)
            .order_by("-created_at")
            .first()
        )
        if doc is None:
            LegalDocument.objects.create(
                doc_type=doc_type,
                version=spec["version"],
                title=spec["title"],
                content=contents[doc_type],
                is_active=True,
                effective_at=effective_at,
            )
        else:
            doc.version = spec["version"]
            doc.title = spec["title"]
            doc.content = contents[doc_type]
            doc.is_active = True
            doc.effective_at = effective_at
            doc.save(update_fields=["version", "title", "content", "is_active", "effective_at", "updated_at"])


def noop(apps, schema_editor):
    """No se revierte el contenido: es la fuente canónica del documento activo."""


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_legaldocument"),
    ]

    operations = [
        migrations.RunPython(upsert_documents, noop),
    ]