# Generated by Django 5.2.17 on 2026-08-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_seed_legal_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_onboarded",
            field=models.BooleanField(
                default=False,
                help_text="True cuando el usuario ya completó el tour guiado de Navi.",
                verbose_name="Tutorial visto",
            ),
        ),
    ]
