# Generated by Django 5.2.17 on 2026-08-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_deletion_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='navi_learning_consent_at',
            field=models.DateTimeField(blank=True, help_text='Fecha del último cambio de preferencia de aprendizaje. Null = no preguntado aún.', null=True, verbose_name='Consentimiento de aprendizaje el'),
        ),
        migrations.AddField(
            model_name='user',
            name='navi_learning_mode',
            field=models.CharField(choices=[('none', 'Ninguno'), ('manual', 'Solo manual'), ('full', 'Completo')], default='none', help_text='none = Navi no recuerda nada; manual = solo «recuerda que…»; full = aprendizaje automático + manual.', max_length=8, verbose_name='Modo de aprendizaje de Navi'),
        ),
    ]
