# Generated by Django 5.2.17 on 2026-08-04 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('label', models.CharField(max_length=60, verbose_name='Etiqueta')),
                ('kind', models.CharField(choices=[('transaction', 'Nueva operación'), ('goal_contribution', 'Aportar a meta')], max_length=30, verbose_name='Tipo')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuración')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('icon', models.CharField(blank=True, default='zap', max_length=40, verbose_name='Icono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Atajo',
                'verbose_name_plural': 'Atajos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
