# Generated by Django 5.2.17 on 2026-09-24 20:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0006_transfer_integrity_checks'),
        ('wallets', '0006_partial_unique_wallet_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('currency', models.CharField(choices=[('USD', '$ — Dólar estadounidense'), ('VES', 'Bs — Bolívar (VES)'), ('EUR', '€ — Euro')], default='USD', max_length=3, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('completada', 'Completada')], default='en_curso', max_length=12, verbose_name='Estado')),
                ('total_real', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total real')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada el')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete (C4): la lista se oculta de la API pero conserva su historial.', verbose_name='Oculta')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list', to='transactions.transaction', verbose_name='Operación generada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_lists', to='wallets.wallet', verbose_name='Cuenta del pago')),
            ],
            options={
                'verbose_name': 'Lista de compras',
                'verbose_name_plural': 'Listas de compras',
                'ordering': ['-created_at'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=120, verbose_name='Producto')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio por unidad')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Marcado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.shoppinglist', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user', 'estado'], name='checklists__user_id_c74bff_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user', 'created_at'], name='checklists__user_id_a859e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['en_curso', 'completada'])), name='checklist_estado_valid', violation_error_message='Estado de lista inválido.'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.CheckConstraint(condition=models.Q(('total_real__isnull', True), ('total_real__gt', 0), _connector='OR'), name='checklist_total_real_gt_0', violation_error_message='El total real debe ser mayor a cero.'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.CheckConstraint(condition=models.Q(('estado', 'en_curso'), models.Q(('wallet__isnull', False), ('transaction__isnull', False)), _connector='OR'), name='checklist_completada_con_pago', violation_error_message='Al completar la lista debes indicar la cuenta y generar la operación.'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.CheckConstraint(condition=models.Q(('estado', 'en_curso'), ('completed_at__isnull', False), _connector='OR'), name='checklist_completada_con_fecha', violation_error_message='Una lista completada requiere la fecha de cierre.'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['checklist', 'is_checked'], name='checklists__checkli_c775c7_idx'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['checklist', 'created_at'], name='checklists__checkli_712a26_idx'),
        ),
        migrations.AddConstraint(
            model_name='listitem',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__isnull', True), ('precio_unitario__gt', 0), _connector='OR'), name='checklistitem_precio_unitario_gt_0', violation_error_message='El precio por unidad debe ser mayor a cero.'),
        ),
        migrations.AddConstraint(
            model_name='listitem',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='checklistitem_cantidad_gte_1', violation_error_message='La cantidad debe ser al menos 1.'),
        ),
    ]
