# Generated by Django 5.2.17 on 2026-10-02 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('currency', models.CharField(choices=[('USD', '$ — Dólar estadounidense'), ('VES', 'Bs — Bolívar (VES)'), ('EUR', '€ — Euro')], max_length=3, verbose_name='Moneda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='business_bu_user_id_71842a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user',), name='uniq_business_per_user')],
            },
        ),
    ]
