# Generated by Django 5.2.17 on 2026-08-04 19:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('currency', models.CharField(choices=[('USD', '$ — Dólar estadounidense'), ('VES', 'Bs — Bolívar (VES)'), ('EUR', '€ — Euro')], max_length=3, verbose_name='Moneda')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo actual; se ajusta automáticamente con los pagos y manualmente por el usuario.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Saldo')),
                ('tipo', models.CharField(choices=[('cash', 'Efectivo'), ('bank', 'Banco'), ('other', 'Otro')], default='cash', max_length=10, verbose_name='Tipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='uniq_wallet_name_per_user')],
            },
        ),
    ]
