# Generated by Django 5.2.17 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="color",
            field=models.CharField(
                blank=True,
                default="#006a61",
                help_text="Color identificador (hex) que armoniza con el tema glass.",
                max_length=9,
                verbose_name="Color",
            ),
        ),
    ]
