# Generated by Django 5.2.17 on 2026-08-10 00:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_wallet_tipo_ahorro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('saldo__gte', Decimal('0'))), name='wallet_saldo_gte_0', violation_error_message='El saldo no puede ser negativo.'),
        ),
    ]
