# Generated by Django 5.2.17 on 2026-08-10 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_wallet_wallet_saldo_gte_0'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=2, help_text='Delta aplicado (positivo suma, negativo resta).', max_digits=20, verbose_name='Variación')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Saldo resultante')),
                ('reason', models.CharField(blank=True, default='', help_text='Ej: ajuste_manual, transaction-<id>, transfer-in/out.', max_length=120, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Registro de auditoría de saldo',
                'verbose_name_plural': 'Registros de auditoría de saldos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'default_manager_name': 'objects', 'ordering': ['created_at'], 'verbose_name': 'Billetera', 'verbose_name_plural': 'Billeteras'},
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete (C4): la billetera se oculta de la API pero conserva su historial.', verbose_name='Oculta'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='color',
            field=models.CharField(blank=True, default='#006a61', help_text='Color identificador (hex) que armoniza con el glass.', max_length=9, verbose_name='Color'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'is_deleted'], name='wallets_wal_user_id_722b72_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'created_at'], name='wallets_wal_user_id_0117c7_idx'),
        ),
        migrations.AddField(
            model_name='balanceauditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Dueño de la billetera al momento del ajuste.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='balanceauditlog',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='wallets.wallet', verbose_name='Billetera'),
        ),
        migrations.AddIndex(
            model_name='balanceauditlog',
            index=models.Index(fields=['wallet', '-created_at'], name='wallets_bal_wallet__8579e1_idx'),
        ),
    ]
