# Generated by Django 5.2.17 on 2026-10-02 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('wallets', '0006_partial_unique_wallet_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='business',
            field=models.OneToOneField(blank=True, help_text='Negocio al que pertenece la billetera (si es de negocio).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='business.business', verbose_name='Negocio'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='tipo',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('bank', 'Banco'), ('saving', 'Ahorro'), ('other', 'Otro'), ('business', 'Negocio')], default='cash', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['business'], name='wallets_wal_busines_d0ec22_idx'),
        ),
    ]
