# Generated by Django 5.2.17 on 2026-10-02 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('tax_id', models.CharField(blank=True, default='', max_length=30, verbose_name='RIF/NIT')),
                ('type', models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('ambos', 'Ambos')], default='cliente', max_length=10, verbose_name='Tipo')),
                ('customer_type', models.CharField(blank=True, choices=[('minorista', 'Minorista'), ('mayorista', 'Mayorista')], default='', max_length=10, verbose_name='Tipo de cliente')),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=0, verbose_name='Días de crédito')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Límite de crédito')),
                ('currency', models.CharField(choices=[('USD', '$ — Dólar estadounidense'), ('VES', 'Bs — Bolívar (VES)'), ('EUR', '€ — Euro')], default='USD', max_length=3, verbose_name='Moneda del límite')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='business.business', verbose_name='Negocio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contacto de negocio',
                'verbose_name_plural': 'Contactos de negocio',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'business', 'name'], name='crm_contact_ub_name_idx'), models.Index(fields=['user', 'business', 'type'], name='crm_contact_ub_type_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tax_id__gt', '')), fields=('business', 'tax_id'), name='uniq_business_contact_tax_id')],
            },
        ),
    ]
