# Generated by Django 5.2.17 on 2026-10-03 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('crm', '0001_initial'),
        ('transactions', '0006_transfer_integrity_checks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('issue_date', models.DateField(verbose_name='Fecha de emisión')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='borrador', max_length=10, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto pagado')),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Saldo pendiente')),
                ('currency', models.CharField(choices=[('USD', '$ — Dólar estadounidense'), ('VES', 'Bs — Bolívar (VES)'), ('EUR', '€ — Euro')], default='USD', max_length=3, verbose_name='Moneda')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='business.business', verbose_name='Negocio')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.businesscontact', verbose_name='Contacto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('description', models.CharField(max_length=160, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.invoice', verbose_name='Factura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Línea de factura',
                'verbose_name_plural': 'Líneas de factura',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Nota')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.invoice', verbose_name='Factura')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payments', to='transactions.transaction', verbose_name='Operación de cobro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago de factura',
                'verbose_name_plural': 'Pagos de facturas',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'business', 'status'], name='crm_inv_ub_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'business', 'due_date'], name='crm_inv_ub_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('business', 'number'), name='uniq_business_invoice_number'),
        ),
    ]
