# Generated by Django 5.2.17 on 2026-10-03 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_invoice_invoiceitem_invoicepayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('channel', models.CharField(choices=[('llamada', 'Llamada'), ('email', 'Correo'), ('whatsapp', 'WhatsApp'), ('visita', 'Visita'), ('otro', 'Otro')], max_length=10, verbose_name='Canal')),
                ('outcome', models.CharField(choices=[('sin_respuesta', 'Sin respuesta'), ('promesa_pago', 'Promesa de pago'), ('pago_realizado', 'Pago realizado'), ('rechazado', 'Rechazado'), ('otro', 'Otro')], max_length=16, verbose_name='Resultado')),
                ('promised_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago prometida')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='crm.invoice', verbose_name='Factura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Seguimiento de cobranza',
                'verbose_name_plural': 'Seguimientos de cobranza',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'invoice', 'created_at'], name='crm_followup_ui_created')],
            },
        ),
    ]
