# Generated by Django 5.2.17 on 2026-10-03 01:16

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('crm', '0003_collectionfollowup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('sku', models.CharField(blank=True, default='', max_length=40, verbose_name='Código/SKU')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('unit', models.CharField(blank=True, default='unidad', max_length=12, verbose_name='Unidad de medida')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio de venta')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Precio mayorista')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Costo de compra')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Existencias')),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Alerta de stock mínimo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.business', verbose_name='Negocio')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='crm.businesscontact', verbose_name='Proveedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='crm.product', verbose_name='Producto del catálogo'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='business.business', verbose_name='Negocio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de producto',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='crm.productcategory', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Variación de existencias')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Motivo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='crm.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ajuste de inventario',
                'verbose_name_plural': 'Ajustes de inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['user', 'business', 'name'], name='crm_prod_cat_ub_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('business'), name='uniq_business_product_category_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'business', 'name'], name='crm_prod_ub_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'business', 'sku'], name='crm_prod_ub_sku_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('business'), name='uniq_business_product_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__gt', '')), fields=('business', 'sku'), name='uniq_business_product_sku'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='ck_product_stock_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ck_product_unit_price_nonneg'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['user', 'product', 'created_at'], name='crm_stkadj_up_created_idx'),
        ),
    ]
