# Generated by Django 5.2.17 on 2026-10-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_product_invoiceitem_product_productcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('unidad', 'Unidad'), ('kg', 'Kg')], default='unidad', max_length=12, verbose_name='Unidad de medida'),
        ),
    ]
