# Generated by Django 5.2.17 on 2026-10-07 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('crm', '0005_product_unit_choices'),
        ('transactions', '0006_transfer_integrity_checks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('order_date', models.DateField(verbose_name='Fecha del pedido')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('en_camino', 'En camino'), ('pagado', 'Pagado'), ('recibido', 'Recibido'), ('anulado', 'Anulado')], default='borrador', max_length=10, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Subtotal')),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto pagado')),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Saldo pendiente')),
                ('currency', models.CharField(choices=[('USD', '$ — Dólar estadounidense'), ('VES', 'Bs — Bolívar (VES)'), ('EUR', '€ — Euro')], default='USD', max_length=3, verbose_name='Moneda')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='business.business', verbose_name='Negocio')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.businesscontact', verbose_name='Proveedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('new_product', models.JSONField(blank=True, default=dict, verbose_name='Datos del producto nuevo')),
                ('description', models.CharField(max_length=160, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='crm.product', verbose_name='Producto del catálogo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Línea de pedido',
                'verbose_name_plural': 'Líneas de pedido',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Nota')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.order', verbose_name='Pedido')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payments', to='transactions.transaction', verbose_name='Operación de pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago de pedido',
                'verbose_name_plural': 'Pagos de pedidos',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'business', 'status'], name='crm_order_ub_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'business', 'order_date'], name='crm_order_ub_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('business', 'number'), name='uniq_business_order_number'),
        ),
    ]
