# Generated by Django 5.2.17 on 2026-10-07

from django.db import migrations, models


def remap_pagado_to_en_camino(apps, schema_editor):
    Order = apps.get_model("crm", "Order")
    Order.objects.filter(status="pagado").update(status="en_camino")


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_order_orderitem_orderpayment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("en_camino", "En camino"),
                    ("recibido", "Recibido"),
                    ("anulado", "Anulado"),
                ],
                default="borrador",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
        migrations.RunPython(
            remap_pagado_to_en_camino, migrations.RunPython.noop
        ),
    ]