# Generated by Django 5.2.17 on 2026-10-08 21:29

from decimal import Decimal
from datetime import timedelta

from django.db import migrations, models
from django.db.models import F


def backfill_crm_data(apps, schema_editor):
    """Congela costos históricos y completa fechas de recibo.

    - ``Order.received_at``: aproximación con ``created_at`` para pedidos ya
      recibidos (no se conoce la hora real del recibo).
    - ``Order.due_date``: pedidos sin vencimiento se completan con los días de
      crédito del proveedor (mismo criterio que ``create_order``).
    - ``InvoiceItem.cost_price`` / ``OrderItem.cost_price``: se rellenan desde
      ``Product.cost_price`` (o el ``cost_price`` declarado del producto nuevo,
      con respaldo al ``unit_price`` de la línea).
    - Categoría por defecto de las operaciones CRM existentes (donut de
      analíticas): cobros de factura → "Venta", pagos de pedido → "Otros".
      Solo si el usuario conserva esas categorías por defecto.
    """
    InvoiceItem = apps.get_model("crm", "InvoiceItem")
    Order = apps.get_model("crm", "Order")
    OrderItem = apps.get_model("crm", "OrderItem")
    InvoicePayment = apps.get_model("crm", "InvoicePayment")
    OrderPayment = apps.get_model("crm", "OrderPayment")
    Category = apps.get_model("transactions", "Category")

    Order.objects.filter(status="recibido", received_at__isnull=True).update(
        received_at=F("created_at")
    )

    for order in Order.objects.select_related("contact").filter(due_date__isnull=True):
        days = order.contact.payment_terms_days or 0
        if days:
            order.due_date = order.order_date + timedelta(days=days)
            order.save(update_fields=["due_date"])

    for item in InvoiceItem.objects.filter(cost_price__isnull=True, product_id__isnull=False):
        product = item.product
        if product is not None and product.cost_price is not None:
            item.cost_price = product.cost_price
            item.save(update_fields=["cost_price"])

    for item in OrderItem.objects.filter(cost_price__isnull=True):
        cost = None
        if item.product_id is not None:
            product = item.product
            cost = product.cost_price if product is not None else None
        if cost is None:
            raw = (item.new_product or {}).get("cost_price")
            cost = Decimal(str(raw)) if raw else item.unit_price
        if cost is not None:
            item.cost_price = cost
            item.save(update_fields=["cost_price"])

    for payment in InvoicePayment.objects.filter(transaction__isnull=False):
        tx = payment.transaction
        if tx.category_id is not None:
            continue
        category = (
            Category.objects.filter(user_id=tx.user_id, name="Venta", tipo="ingreso")
            .values_list("id", flat=True)
            .first()
        )
        if category is not None:
            tx.category_id = category
            tx.save(update_fields=["category_id"])

    for payment in OrderPayment.objects.filter(transaction__isnull=False):
        tx = payment.transaction
        if tx.category_id is not None:
            continue
        category = (
            Category.objects.filter(user_id=tx.user_id, name="Otros", tipo="egreso")
            .values_list("id", flat=True)
            .first()
        )
        if category is not None:
            tx.category_id = category
            tx.save(update_fields=["category_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_order_status_remap_pagado"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="cost_price",
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Costo del producto congelado al emitir la factura.", max_digits=20, null=True, verbose_name="Costo de compra"),
        ),
        migrations.AddField(
            model_name="order",
            name="due_date",
            field=models.DateField(blank=True, help_text="Fecha prevista de pago; en falta, la calcula el contacto (días de crédito).", null=True, verbose_name="Fecha de vencimiento"),
        ),
        migrations.AddField(
            model_name="order",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Recibido el"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cost_price",
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Costo del producto congelado al crear el pedido.", max_digits=20, null=True, verbose_name="Costo de compra"),
        ),
        migrations.RunPython(backfill_crm_data, migrations.RunPython.noop),
    ]