# Generated by Django 5.2.17 on 2026-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('oficial', 'Oficial (BCV)'), ('paralelo', 'Paralelo'), ('manual', 'Manual')], max_length=12, verbose_name='Fuente')),
                ('currency', models.CharField(default='VES', max_length=3, verbose_name='Moneda cotizada')),
                ('compra', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Compra')),
                ('venta', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Venta')),
                ('promedio', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Promedio')),
                ('rate_date', models.DateTimeField(verbose_name='Fecha de la cotización')),
                ('is_stale', models.BooleanField(default=False, help_text='True si provino de una caché sin confirmación reciente.', verbose_name='Desactualizada')),
                ('input_at', models.DateTimeField(auto_now_add=True, verbose_name='Guardada el')),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasas de cambio',
                'ordering': ['-input_at'],
                'indexes': [models.Index(fields=['source', 'input_at'], name='rates_excha_source_a424b6_idx')],
            },
        ),
    ]
