# Generated by Django 5.2.17 on 2026-08-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        ('wallets', '0003_wallet_tipo_ahorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='linked_accounts',
            field=models.ManyToManyField(blank=True, related_name='linked_goals', to='wallets.wallet', verbose_name='Cuentas de ahorro afiliadas'),
        ),
    ]
