# Generated by Django 5.2.17 on 2026-08-10 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingsgoal_linked_accounts'),
        ('wallets', '0005_balanceauditlog_alter_wallet_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcontribution',
            name='goal',
            field=models.ForeignKey(help_text='PROTECT (C4): una meta con aportes nunca se borra en cascada; el historial de aportes es permanente.', on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='savings.savingsgoal', verbose_name='Meta'),
        ),
        migrations.AddIndex(
            model_name='goalcontribution',
            index=models.Index(fields=['goal', '-created_at'], name='savings_goa_goal_id_aded51_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['user', 'created_at'], name='savings_sav_user_id_297a84_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalcontribution',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='goalcontribution_amount_gt_0', violation_error_message='El aporte debe ser mayor a cero.'),
        ),
    ]
