# Generated by Django 5.2.17 on 2026-08-06 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('kind', models.CharField(choices=[('due_soon', 'Vence pronto'), ('overdue', 'Vencida'), ('goal_reached', 'Meta alcanzada'), ('system', 'Sistema')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('message', models.CharField(max_length=255, verbose_name='Mensaje')),
                ('read', models.BooleanField(default=False, verbose_name='Leída')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Referencias')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
