# Generated by Django 5.2.17 on 2026-08-24 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notif_user_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('due_soon', 'Vence pronto'), ('overdue', 'Vencida'), ('goal_reached', 'Meta alcanzada'), ('expense_nudge', 'Recordatorio de registro'), ('system', 'Sistema')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='Endpoint push')),
                ('p256dh', models.CharField(max_length=120, verbose_name='Clave p256dh')),
                ('auth', models.CharField(max_length=60, verbose_name='Secreto auth')),
                ('user_agent', models.CharField(blank=True, default='', max_length=200, verbose_name='Navegador')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Último envío OK')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción push',
                'verbose_name_plural': 'Suscripciones push',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='push_user_idx')],
            },
        ),
    ]
