# Generated by Django 5.2.17 on 2026-10-02 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_kind_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='uniq_notification_user_kind_extra',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_user_read_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='scope',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Negocio')], db_index=True, default='personal', max_length=10, verbose_name='Ámbito'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'scope', '-created_at'], name='notif_user_scope_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'scope', 'read'], name='notif_user_scope_read_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'scope', 'kind', 'extra'), name='uniq_notification_user_scope_kind_extra'),
        ),
    ]
