# Generated by Django 5.2.17 on 2026-10-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_uniq_notification_user_kind_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('due_soon', 'Vence pronto'), ('overdue', 'Vencida'), ('goal_reached', 'Meta alcanzada'), ('expense_nudge', 'Recordatorio de registro'), ('invoice_overdue', 'Factura vencida'), ('invoice_paid', 'Factura pagada'), ('system', 'Sistema')], max_length=20, verbose_name='Tipo'),
        ),
    ]
