# Generated by Django 5.2.17 on 2026-10-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('due_soon', 'Vence pronto'), ('overdue', 'Vencida'), ('goal_reached', 'Meta alcanzada'), ('expense_nudge', 'Recordatorio de registro'), ('invoice_overdue', 'Factura vencida'), ('invoice_paid', 'Factura pagada'), ('product_low_stock', 'Stock bajo'), ('system', 'Sistema')], max_length=20, verbose_name='Tipo'),
        ),
    ]
